<?php
define("ERROR_PASSWORD_MISMATCH" , "PASSWORD_MISMATCH");
define("ERROR_EMAIL_INVALID" , "EMAIL_INVALID");
define("ERROR_EMAIL_TAKEN" , "EMAIL_TAKEN");
define("ERROR_SAVING_FAIL" , "SAVING_FAIL");
define('INVALID_POST', 'INVALID_POST');
