<?php
define("PRIVATE_MODE" , 1);
define("PUBLIC_MODE", 2);
define("TEAM_MODE", 3);

define("ROUTE_SUCCESSFULLY_SAVED", "ROUTE_SUCCESSFULLY_SAVED");
define("NOT_ENOUGH_DATA", "NOT_ENOUGH_DATA");
define("TEAM_REQUIRED", "TEAM_REQUIRED");