<?php

define("TEAM_SUCCESSFULLY_SAVED", "TEAM_SUCCESSFULLY_SAVED");
define("TEAM_SAVING_FAILED", "TEAM_SAVING_FAILED");
define("TEAM_SUCCESSFULLY_DELETED", "TEAM_SUCCESSFULLY_DELETED");
define("TEAM_MEMBER_REMOVED", "TEAM_MEMBER_REMOVED");
define("TEAM_MEMBER_ADDED", "TEAM_MEMBER_ADDED");
define("TEAM_MEMBER_ALREADY_EXISTS", "TEAM_MEMBER_ALREADY_EXISTS");